#!/bin/bash
 
#SBATCH --job-name=nextflow_run
#SBATCH --time=1-00:00:00
#SBATCH --qos=1day
#SBATCH --output=nextflow_run.o%j
#SBATCH --error=nextflow_run.e%j

# the "--time" and "--qos" flags determine the overall running of the workflow
# while the flags in the "conf/envs/.config" files determine running of the individual jobs
# feel free to change the parameters to fit your situation

nextflow run main.nf -profile <profile of your choice>,<profile that fits your work environment>


