name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - dev

jobs:

  test_linux:   
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-20.04]
    
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup miniconda & small_peptides root env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7.4
          miniconda-version: 4.7.12
          auto-update-conda: false
          environment-file: install/environment.yml
          activate-environment: small_peptides
          auto-activate-base: false
          
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies via pip
        run: |
          pip install zenodo-get
        
      - name: Get data via zenodo
        run: |
          zenodo_get 7085656 -o zenodo/
          ls -la zenodo/
          
      - name: Install singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3

      - name: Update small_peptides env with dev. packages
        run: conda env update -f install/environment.dev.yml

      - name: Display some debugging info
        run: |
          singularity --version
          nextflow -version
          conda info -a
          conda list
        
      - name: Pull singularity images
        run: bash data/scripts/pull_containers.sh
        
      - name: run nextflow
        run: nextflow run main.nf -profile test,slurm_offline
        
        
  test_macos:   
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-12]
    
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup miniconda & small_peptides root env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7.4
          miniconda-version: 4.7.12
          auto-update-conda: false
          environment-file: install/environment.yml
          activate-environment: small_peptides
          auto-activate-base: false
        
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install dependencies via pip
        run: |
          pip install zenodo-get
        
      - name: Get data via zenodo
        run: |
          zenodo_get 7085656 -o zenodo/
          ls -la zenodo/
          
      - name: Install docker
        run: |
         brew install docker
         brew install colima
         colima start
         docker ps -a
         docker run hello-world

      - name: Update small_peptides env with dev. packages
        run: conda env update -f install/environment.dev.yml

      - name: Display all miniconda & env info
        run: |
          docker --version
          nextflow -version
          conda info -a
          conda list

      - name: Pull singularity images
        run: bash data/scripts/pull_containers.sh

